"""Initial migration

Revision ID: dfeb204014ac
Revises: 
Create Date: 2024-07-29 23:20:44.900286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfeb204014ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistema_xx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema_xx_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_specie_sistema_xx', 'sistema_xx', ['sistema_xx_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.drop_constraint('fk_specie_sistema_xx', type_='foreignkey')
        batch_op.drop_column('sistema_xx_id')

    op.drop_table('sistema_xx')
    # ### end Alembic commands ###
